syms Pa Vwn S Vb Fd Fm Wx rhow Patm Sb dVb mb ma mw dVwn
eqns=[Pa*Vwn*S-Vb*(Fd+Fm+Wx)-rhow*Vwn*S*((Patm/rhow)+Vb*Vwn*((S/Sb)-1)-(Vwn^2/2)*((S/Sb)^2-1))==...
    dVb*(mb*Vb+ma*Vb+mw*Vb-mw*Vwn*(S/Sb))+dVwn*(mw*Vwn*(S^2/Sb^2)-mw*Sb*(S/Sb)),...
    Fd+Fm+Wx-rhow*Vwn*S*((Vwn*(S/Sb)-1))==...
    dVb*(mb+ma+mw)+dVwn*(-mw*(S/Sb))];
S=solve(eqns,[dVb dVwn]);

str1=latex(S.dVb);
str2=latex(S.dVwn);